#!/usr/bin/env python3
"""

CONTROLLA CHE IL RASPBERRY ABBIA LA TECNOLOGIA PER FARE LA LOCALIZZAZIONE CON ALTA
PRECISIONE, SENNO VA RIDIMENSIONATO IL METODO USATO PER QUESTA TECONOLOGIA



Time and Place Synchronization Module

This module handles network connectivity checks, automatic reconnection via NetworkManager,
high-precision Wi-Fi geolocation using the Mozilla Location Service, reverse geocoding via OpenStreetMap,
IP-based location as fallback, system timezone updates, and local configuration persistence.
"""

import json
import datetime
import subprocess
import time
import config
import requests


def check_internet_connection():
    """
    Check for internet connectivity by pinging Google.

    Returns:
        bool: True if internet is reachable (HTTP 200), False otherwise.
    """

    try:
        # Try to connect to a well-known website (Google) to check for internet connectivity
        response = requests.get("https://www.google.com", timeout=5)
        return response.status_code == 200
    except requests.RequestException:
        return False

def try_connection_to_known_networks():
    """
    Attempt automatic reconnection to known Wi-Fi networks using NetworkManager.

    Returns:
        bool: True if connection is successfully established, False otherwise.
    """

    print("Currently offline. Attempting automatic reconnection to known networks...")

    # Enable networking and trigger autoconnect via NetworkManager
    subprocess.run(["nmcli", "networking", "on"])

    # Wait for the connection to establish
    time.sleep(5)

    return check_internet_connection()

def scan_wifi_networks():
    """
    Scan nearby Wi-Fi networks and extract their MAC addresses and signal strengths.

    Returns:
        list[dict]: A list of dictionaries containing 'macAddress' and 'signalStrength'.
    """

    try:
        # Run the NetworkManager (nmcli) system command to scan for Wi-Fi.
        # -t (terse) outputs in a clean, parsable format.
        # -f BSSID,SIGNAL selects only the router's MAC address and signal strength.
        result = subprocess.run(
            ["nmcli", "-t", "-f", "BSSID,SIGNAL", "dev", "wifi"],
            capture_output=True, # Captures the text output generated by the command
            text=True,           # Converts the output into readable Python strings
            check=True           # Raises an exception if the command fails
        )
        
        networks = []
        for line in result.stdout.splitlines():
            # Split the line using the colon character as a separator
            parts = line.split(":")

            # Ensure the line contains enough parts to form a valid BSSID (MAC address)
            if len(parts) >= 6:
                bssid = ":".join(parts[:6])  # Reconstruct the MAC address from the first 6 parts
                signal = parts[-1]            # The last part represents the signal strength

                # Check if the BSSID is valid before adding it
                if bssid and bssid != "--":
                    try:
                        # Append a structured dictionary with MAC and signal to the list
                        networks.append({
                            "macAddress": bssid,
                            "signalStrength": int(signal)
                        })
                    except ValueError:
                        continue
        return networks
    except Exception as e:
        print(f"Error scanning Wi-Fi networks: {e}")
        return []

def fetch_location_from_wifi():
    """
    Use Mozilla Location Service (MLS) via nearby Wi-Fi networks to get precise coordinates.

    Returns:
        tuple[float, float] | None: A tuple containing (latitude, longitude), or None if it fails.
    """

    # Step 1: Get the list of nearby Wi-Fi networks with their MAC addresses and signal strengths
    wifi_list = scan_wifi_networks()
    if not wifi_list:
        return None

    # Step 2: Define the Mozilla Location Service public API endpoint
    url = "https://location.services.mozilla.com/v1/geolocate?key=test"
    # Prepare the payload with the required JSON structure expected by the API
    payload = {"wifiAccessPoints": wifi_list}
    
    try:
        # Step 3: Send a POST request to the API with a 5-second timeout
        response = requests.post(url, json=payload, timeout=5)
        if response.status_code == 200:
            data = response.json()

            # Extract latitude and longitude from the JSON response
            lat = data.get("location", {}).get("lat")
            lng = data.get("location", {}).get("lng")

            # Return coordinates if both latitude and longitude are present
            if lat and lng:
                return lat, lng
            
    except requests.RequestException as e:
        print(f"Mozilla Location Service error: {e}")
    
    return None

def get_city_from_coords(lat, lng):
    """
    Convert latitude and longitude into a city and country name via OpenStreetMap Nominatim.

    Args:
        lat (float): Latitude coordinate.
        lng (float): Longitude coordinate.

    Returns:
        tuple[str | None, str | None]: A tuple containing (city_name, country_name) or (None, None).
    """

    # Construct the OpenStreetMap Nominatim reverse geocoding API URL with coordinates
    url = f"https://nominatim.openstreetmap.org/reverse?format=json&lat={lat}&lon={lng}"

    # Define required headers (Nominatim policy requires a unique User-Agent identifier)
    headers = {'User-Agent': 'RaspberryPiLocationSync/1.0'}
    
    try:
        # Send an HTTP GET request to the Nominatim API with a 5-second timeout
        response = requests.get(url, headers=headers, timeout=5)
        if response.status_code == 200:
            data = response.json()
            address = data.get("address", {})

            # Extract the city name, falling back through common address fields if necessary
            city = address.get("city") or address.get("town") or address.get("village") or address.get("municipality")
            country = address.get("country")

            return city, country
        
    except requests.RequestException as e:
        print(f"Nominatim reverse geocoding error: {e}")
    
    return None, None

def fetch_location_fallback_ip():
    """
    Retrieve location data based on public IP as a fallback when Wi-Fi geolocation fails.

    Returns:
        dict | None: Dictionary with 'city', 'country', and 'timezone', or None.
    """

    try:
        # Send an HTTP GET request to the public IP geolocation API with a 5-second timeout
        response = requests.get("http://ip-api.com/json/", timeout=5)
        data = response.json()

        if data.get("status") == "success":
            # Return a dictionary containing the IP-based location details
            return {
                "city": data.get("city"),
                "country": data.get("country"),
                "timezone": data.get("timezone")
            }
        
    except requests.RequestException as e:
        print(f"Error fetching IP location fallback: {e}")
    return None

def fetch_location_data():
    """
    Retrieve location data by trying high-precision Wi-Fi geolocating first, 
    and falling back to IP-based geolocation if Wi-Fi fails.

    Returns:
        dict | None: Dictionary containing 'city', 'country', and 'timezone', or None.
    """

    # Step 1: Attempt high-precision geolocation using nearby Wi-Fi networks
    print("Attempting high-precision Wi-Fi geolocation...")
    coords = fetch_location_from_wifi()

    # Step 2: If coordinates were successfully found via Wi-Fi, use them to get the city and country
    if coords:
        lat, lng = coords
        city, country = get_city_from_coords(lat, lng)
        # If the reverse geocoding successfully retrieved a city name
        if city:
            # Fetch IP data just to retrieve the correct timezone (or default to 'Europe/Rome')
            ip_data = fetch_location_fallback_ip()
            timezone = ip_data.get("timezone") if ip_data else "Europe/Rome"
            
            return {
                "city": city,
                "country": country or "Unknown",
                "timezone": timezone
            }

    # Step 3: Fallback if Wi-Fi geolocation is unavailable or failed
    print("Wi-Fi geolocation unavailable or failed. Falling back to IP-based location...")
    return fetch_location_fallback_ip()

def update_system_timezone(timezone):
    """
    Update the system timezone using the Linux timedatectl utility.

    Args:
        timezone (str): The valid timezone string to set (e.g., 'Europe/Rome').
    """
    subprocess.run(["sudo", "timedatectl", "set-timezone", timezone])

def save_location_config(location_info):
    """
    Save the synchronized location and timezone details to a local JSON configuration file.

    Args:
        location_info (dict): Dictionary containing city, country, and timezone details.
    """

    # Create a dictionary containing the location details along with an ISO-formatted timestamp of the sync
    data_config = {
        "city": location_info["city"],
        "country": location_info["country"],
        "timezone": location_info["timezone"],
        "last_sync": datetime.datetime.now().isoformat()
    }
    # Open the configuration file in write mode and dump the dictionary as formatted JSON
    with open(config.TIME_PLACE_JSON_CONFIG_PATH, "w") as f:
        json.dump(data_config, f, indent=4)

def sync_time_and_place():
    """
    Orchestrate the full synchronization process by fetching location data,
    updating the system timezone, and saving the configuration locally.

    Returns:
        bool: True if synchronization succeeded, False otherwise.
    """
    print("Synchronizing time and place...")

    # Step 1: Fetch location and timezone details using Wi-Fi or IP fallback
    location_data = fetch_location_data()
    if not location_data:
        print("Failed to retrieve location data.")
        return False

    print(f"Location found: {location_data['city']}, {location_data['country']}, Timezone: {location_data['timezone']}")

    # Step 2: Apply the timezone update to the system and save configuration to disk
    update_system_timezone(location_data["timezone"])
    save_location_config(location_data)

    print("Time and place synchronized successfully.")
    return True

def handle_time_and_place_sync_action():
    """
    Check for internet connectivity, attempt automatic reconnection if offline,
    and trigger the main time and location synchronization routine.

    Returns:
        bool: True if synchronization completed successfully, False otherwise.
    """

    # Step 1: Check if the device currently has an internet connection
    if not check_internet_connection():
        # If offline, try reconnecting automatically to known Wi-Fi networks
        if not try_connection_to_known_networks():
            print("Unable to synchronize: no internet connection available.\nPlease connect to a Wi-Fi network in the settings.")
            return False

    # Step 2: Proceed with synchronizing time and place once internet is confirmed
    return sync_time_and_place()